# Generated by Django 5.1.5 on 2025-02-02 08:55

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Answer')),
                ('question_hi', models.TextField(blank=True, null=True)),
                ('question_bn', models.TextField(blank=True, null=True)),
                ('answer_hi', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Answer (Hindi)')),
                ('answer_bn', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Answer (Bengali)')),
            ],
        ),
    ]
